// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

const (
	BasicAuthScopes = "BasicAuth.Scopes"
)

// CodeType defines model for code_type.
type CodeType string

// List of CodeType
const (
	CodeType_all   CodeType = "all"
	CodeType_ean13 CodeType = "ean13"
	CodeType_ean8  CodeType = "ean8"
	CodeType_qr    CodeType = "qr"
)

// Read defines model for read.
type Read struct {

	// the payload that the scanner read
	Payload *string `json:"payload,omitempty"`
}

// ScannerInfo defines model for scanner_info.
type ScannerInfo struct {

	// hardware version
	HardwareVersion *string `json:"hardware_version,omitempty"`

	// product model
	Model *string `json:"model,omitempty"`

	// software date
	SoftwareDate *string `json:"software_date,omitempty"`

	// software version
	SoftwareVersion *string `json:"software_version,omitempty"`
}

// Status defines model for status.
type Status struct {

	// Status code
	Code int32 `json:"code"`

	// Status message
	Message string `json:"message"`
}

// SwitchOpt defines model for switch_opt.
type SwitchOpt string

// List of SwitchOpt
const (
	SwitchOpt_disable SwitchOpt = "disable"
	SwitchOpt_enable  SwitchOpt = "enable"
	SwitchOpt_std     SwitchOpt = "std"
)

// Statusresponse defines model for statusresponse.
type Statusresponse Status

// DisableCodeJSONBody defines parameters for DisableCode.
type DisableCodeJSONBody struct {

	// enum with available code types
	CodeType *CodeType `json:"code_type,omitempty"`
}

// EnableCodeJSONBody defines parameters for EnableCode.
type EnableCodeJSONBody struct {

	// enum with available code types
	CodeType *CodeType `json:"code_type,omitempty"`
}

// LightJSONBody defines parameters for Light.
type LightJSONBody struct {

	// enum with light options
	Set *SwitchOpt `json:"set,omitempty"`
}

// DisableCodeJSONRequestBody defines body for DisableCode for application/json ContentType.
type DisableCodeJSONRequestBody DisableCodeJSONBody

// EnableCodeJSONRequestBody defines body for EnableCode for application/json ContentType.
type EnableCodeJSONRequestBody EnableCodeJSONBody

// LightJSONRequestBody defines body for Light for application/json ContentType.
type LightJSONRequestBody LightJSONBody
