// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /info)
	GetInfo(ctx echo.Context) error

	// (GET /test)
	GetTest(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetInfo(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetInfo(ctx)
	return err
}

// GetTest converts echo context to params.
func (w *ServerInterfaceWrapper) GetTest(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTest(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/info", wrapper.GetInfo)
	router.GET(baseURL+"/test", wrapper.GetTest)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xUTW/UMBD9K9bAMWzcLV/KreWAKoSALrfVqnKdycZVYht7QllV+e/IdrIfTRaExC2Z",
	"sd97M/M8TyBNa41GTR6KJ3DordEe448nQZ0fQyEijSbUFD6FtY2SgpTR+YM3Ol6QNbYifL10WEEBL/ID",
	"fJ6yPk+w0Pd9BiV66ZQNKFAMhKxF78UW2aOimg0xaUpkQpdjEsLtATFRC63R3SldmfBvnbHoSKVKauHK",
	"R+Hw7ic6r5LYU+rxBBtPZIC/RGsbhAIuFpxDBrSzGFU6pbfQZ9CaEpsplnWm7CSxlD4G+vj57Zs5IG8q",
	"ivpKQTgFHNMspo8Bl3zJ+SW/+CPo2aL3uGeKnoHt9xFz/4CSIlEa6KTrYWZT0tVhoJBBZVwrCApQmi6X",
	"Bz6lCbfoYpeHiZ9DGvNzWh3+6JTDEoo1DIzj8c2kklAKys4p2q2Cs1IV18IredVRvXd4uHMfogfKmsgm",
	"R48GPJV6LVygz7/dvvoQnLxKdmXBEOzq601AUnTskf3QgC8uFjw0wljUwioo4HLBF2E4VlAdReYj7RZp",
	"yn6L1DnNgsfjG3o+d89MxahGNrwiiFwuPu6bMmhCugkE2emCWHL+/7bC8QOe2Q2rTkr0vuqaZsdcLAhL",
	"lk5n8DopmSPYK86f7bM+suSEnv7SOc++fJrryfdwdb4n/6zkyHxQrE9st970m5B1YVwx2blmMF2R563Q",
	"W1O85+849Jv+dwAAAP//d8CaZtIFAAA=",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
